### ISSUE TITLE
Can't build on Ubuntu 19.10

### ISSUE THREAD

**Issue by lmore377** [MooseTheBrown/psmoveinput#3]
When building without changing anything after installing psmoveapi, this is what I get: [https://pastebin.com/1USJ436x](url)

and if I comment out the line in `CMakeFiles/psmoveinput.dir/build.make` that it errors out on, it pretends to build successfuly but never actually compiles psmoveinput.

**Comment by thp** [comment]
```undefined reference to symbol 'pthread_condattr_setclock@@GLIBC_2.3.3'```

You need to link against pthreads (`-pthread` or `-lpthread`).

**Comment by MooseTheBrown** [comment]
psmoveinput is linked with boost-thread, which should be linked with pthread. At least it is in openSUSE. Maybe explicit linking with pthread is required for Ubuntu, I'll check.

**Comment by lmore377** [comment]
I added -pthread to line 35 in CMakeLists.txt and it built successfully. 
`set (COMMON_CXX_FLAGS "-std=c++0x -pthread")`

**Comment by MooseTheBrown** [comment]
Thanks for the hint.

Fixed in https://github.com/MooseTheBrown/psmoveinput/commit/ada22d2a8bf3b37fec4eeb3c83c1577c219d9a45
